services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
