/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ee',
        'surface-container': '#f0ede9',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e5e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#544437',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f3f0eb',
        outline: '#877365',
        'outline-variant': '#dac2b1',
        'surface-tint': '#8f4e00',
        primary: '#8f4e00',
        'on-primary': '#ffffff',
        'primary-container': '#ff9f43',
        'on-primary-container': '#6d3a00',
        'inverse-primary': '#ffb77a',
        'primary-fixed': '#ffdcc2',
        'primary-fixed-dim': '#ffb77a',
        'on-primary-fixed': '#2e1500',
        'on-primary-fixed-variant': '#6d3a00',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e4e2e1',
        'on-secondary-container': '#656464',
        tertiary: '#655d55',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#bfb4aa',
        'on-tertiary-container': '#4e463e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fcf9f4',
        'on-background': '#1c1c19',
        'surface-variant': '#e5e2dd',
        'tertiary-fixed': '#ede0d6',
        'tertiary-fixed-dim': '#d0c4ba',
        'on-tertiary-fixed': '#201b14',
        'on-tertiary-fixed-variant': '#4d453e',
        'secondary-fixed': '#e4e2e1',
        'secondary-fixed-dim': '#c8c6c6',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'surface-dim': '#dcdad5',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'margin-mobile': '20px',
        'steward-target-min': '44px',
        'touch-target-min': '64px',
      },
      fontFamily: {
        'body-md': ['Nunito Sans', 'sans-serif'],
        'display-elderly': ['Nunito Sans', 'sans-serif'],
        'body-lg-elderly': ['Nunito Sans', 'sans-serif'],
        'label-caps': ['Nunito Sans', 'sans-serif'],
        'headline-lg': ['Nunito Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-elderly': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'body-lg-elderly': ['20px', { lineHeight: '30px', fontWeight: '600' }],
        'label-caps': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      animation: {
        breathe: 'breathe 4s ease-in-out infinite',
        'pulse-ring': 'pulse-ring 2s cubic-bezier(0.215, 0.61, 0.355, 1) infinite',
      },
      keyframes: {
        breathe: {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.05)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '0.8' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
